sudo: false
language: php
php:
  - '5.4'
  - '5.6'
  - '7.0'
language: node_js
node_js:
  - 7
  - 8
cache:
  directories:
    - node_modules
before_script:
  - npm prune
script:
  - npm run test-cov
after_script:
  - npm install codecov
  - ./node_modules/.bin/codecov