sudo: false
language: php
php:
  - '5.6'
  - '7.0'
  - '7.1'
  - '7.2'
language: node_js
node_js:
  - "8"
  - "9"
  - "10"
cache:
  directories:
    - node_modules
before_script:
  - npm prune
script:
  - npm run test-cov
after_script:
  - npm install codecov
  - ./node_modules/.bin/codecov